use lab_db_var20
go

CREATE TABLE EMPLOYEES
	(ID_EMPLOYEES INT IDENTITY PRIMARY KEY,
	FullName VARCHAR(60) NOT NULL,
	ID_Position INT NOT NULL,
	ID_Department INT NOT NULL)

CREATE TABLE POSITION
	(ID_Position INT IDENTITY PRIMARY KEY,
	Position VARCHAR(60) NOT NULL)

CREATE TABLE DEPARTMENT
	(ID_Department INT IDENTITY PRIMARY KEY,
	Department VARCHAR(60) NOT NULL)

CREATE TABLE ADVERTISEMENTS
	(ID_ADVERTISEMENTS INT IDENTITY PRIMARY KEY,
	ClientFullName VARCHAR(60) NOT NULL,
	ContractDate Date,
	ID_EMPLOYEES INT,
	EndDateContract Date,
	ID_ActionCode INT NOT NULL)

CREATE TABLE ADCOMPONENTS
	(ID_ActionCode INT IDENTITY PRIMARY KEY,
	ServiceType VARCHAR(60) NOT NULL,
	ServicePrice INT,
	EndDateService DATE)







